services:
  db:
    image: mysql:9.0
    volumes:
      - ./infra/mysql-data/:/var/lib/mysql
    restart: "always"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: pp-money
      TZ: "America/Sao_Paulo"

    ports:
      - "33306:3306"

    command: mysqld --sql-mode=NO_ENGINE_SUBSTITUTION